### ISSUE TITLE
Object with [Symbol]

### ISSUE THREAD

**Issue by Jack-Works** [dfahlander/typeson#17]
![image](https://user-images.githubusercontent.com/5390719/70418445-60d5ca00-1a9e-11ea-802d-9cac923d7827.png)

Is it a bug or a feature? It should be `{__raw__map: Array(0), $types: {…}}` at least.

**Comment by brettz9** [comment]
I think we'd need to say this is expected behavior at the moment. Typeson only gives the auto-serialization treatment to plain objects (those with `Object` or `null` as prototype and no `Symbol.toStringTag`), expecting registration of types for any classes with `toStringTag`.

You'd therefore have to register an "a" type which establishes how it should be serialized. Something like this gives the expected result:

```js
import Typeson from '../typeson.js';

const map = {
    map: {
        test (x) { return Typeson.toStringTag(x) === 'Map'; },
        replace (mp) { return [...mp.entries()]; },
        revive (entries) { return new Map(entries); }
    }
};
const aType = {
    a: {
        test (x) { return Typeson.toStringTag(x) === 'a'; },
        replace (n) { return {...n, [Symbol.toStringTag]: undefined}; }
    }
};

const typeson = new Typeson().register([map, aType]);

const a = typeson.encapsulate({
    __raw_map: new Map(),
    [Symbol.toStringTag]: 'a'
});

console.log(a);
// { __raw_map: [], '$types': { __raw_map: 'map' } }
```

In playing around, if @dfahlander is ok with it, it seems that the existing Typeson and typeson-registry tests will all pass though if we continue to reject the cloning of functions, symbols, and objects with `toJSON`, (or Promise/TypesonPromise), but otherwise allow cloning of unknown `toStringTag` objects.

**Comment by dfahlander** [comment]
Sounds good 👍

**Comment by brettz9** [comment]
This is now fixed in typeson v5.15.0 (and within typeson-registry v1.0.0-alpha.31).

Note, however, that although now the `Map` in your example can be properly encapsulated/serialized, the `Symbol.toStringTag` is not preserved after revival--this may require #6 first.

Btw, @dfahlander , while I've got your attention, are you ok with me switching to Mocha for the tests? No promises I'll get to it, but besides the at-a-glance coloring it gives, I like the ability it gives for a quick `it.only` to run only one test.

**Comment by dfahlander** [comment]
It's definitely ok to switch to using Mocha. I'm greatful for all your work with the library!

I will probably be a better contribution to it in future when I will start using it more in a project. For now I've been using it in the dexie-export-import addon some year ago. Just for your knowledge, I had an issue described [here](https://github.com/dfahlander/Dexie.js/blob/master/addons/dexie-export-import/src/tson.ts#L16-L19) that I could work around in that particular library. Theres a [unit test](https://github.com/dfahlander/Dexie.js/blob/master/addons/dexie-export-import/test/basic-tests.ts#L38-L107) that creates a Blob containing all bytes from 0..255 and couldn't serialize it back again to the same content without my workaround.

**Comment by brettz9** [comment]
@dfahlander : I've made the move to Mocha/Chai, thanks!

And would be great to have your expertise taking a look at things whenever you may get the chance again.

I seem to remember maybe already fixing something with Blobs that might be like you describe, but I'm not sure. Hope to take a look as I get a chance, and also on `encapsulateAsync`.

FYI, and this might tie in, as far as the current coverage status... Typeson utility files are now at 100%, but the main Typeson file still has 15% of statements left needing coverage. I see some entire methods are not actually covered, so I wonder if that may be the source of some possible problems as you experienced.

And FWIW, on typeson-registry, we're only missing coverage now on typed-arrays-socket-io (which never had tests), some Blob/File error conditions, and a portion of the `createObjectURL` polyfill which was only needed in IndexedDBShim but seemed the right place since it only added about 4 lines of code and we needed the rest of the polyfill in typeson-registry anyways.

**Comment by brettz9** [comment]
Still hope to take a look at those issues you mentioned, but just wanted to report back that we are now at 100% coverage on both Typeson and typeson-registry, and I've published new npm packages accordingly (not including a few bits of code I've explicitly ignored from coverage in source, as they were either just for simple ignoring of variables when features were not found (e.g., if the environment didn't support `Symbol`) or, in the case of errors during the reading of a `Blob`/`File`, I did not find a ready and realistic way to simulate them).

**Comment by brettz9** [comment]
I've filed https://github.com/dfahlander/Dexie.js/pull/955 now to also fix the unit test you mentioned; all that was needed was to upgrade typeson/typeson-registry.
