### ISSUE TITLE
Failed to build on v7

### ISSUE THREAD

**Issue by Jack-Works** [dfahlander/typeson#27]
webpack reports: 

> export 'Typeson' (imported as 'Typeson') was not found in 'typeson' (module has no exports)

I guess it is because https://github.com/dfahlander/typeson/blob/master/package.json#L11

it should be

```js
      "import": "./dist/typeson.esm.min.js",
      "browser": "./dist/typeson.umd.min.js",
      "require": "./dist/typeson.umd.min.js"
```

Import on the top will fix the problem I guess 🤔

**Comment by brettz9** [comment]
Yeah, that makes more sense (though I put `browser` after `require`). Let me know if that works in v7.0.1. Webpack had some issues previously with `.js` extensions being present in the package which were not used for ESM when `type: module` was used, but hopefully that issue is gone (since browser environments don't all work well in serving the `.cjs` extension).

**Comment by Jack-Works** [comment]
thanks, 7.0.1 works for me!
